<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UserPhoneNo</name>
   <tag></tag>
   <elementGuidId>a9364bc1-3d12-4c20-a63b-728f6b22f4fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[@id='root']/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[3]/div[1]/div[4]/div[1]/input[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
