<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Orderpath</name>
   <tag></tag>
   <elementGuidId>fa81d9c6-54b3-4211-87c8-9e5ac57cdd81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>
//header/div[1]/div[2]/div[1]/button[2]/span[1]/span[1]/*[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
