<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>User_Confirmation</name>
   <tag></tag>
   <elementGuidId>51485a18-96dc-4e61-986b-9f8e03e67c72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>
//body/div[@id='root']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
